spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes: # Spring Cloud Gateway의 라우팅 설정
        - id: auth-service # 라우트 식별자
          uri: lb://auth-service # 'auth-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/v1/auth/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/**   # /api/v1/**로 시작하는 모든 요청을 delivery-service로 라우팅
      discovery:
        locator:
          enabled: true # 서비스 디스커버리를 통해 동적으로 라우트를 생성
server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/